### ISSUE TITLE
子域名数据接口请求异常

### ISSUE THREAD

**Issue by handbye** [CTF-MissFeng/bayonet#37]
![image](https://user-images.githubusercontent.com/26617058/77507183-d70e0900-6ea2-11ea-9812-2051e7d4799f.png)

web日志：

```python
[2020-03-25 14:10:54,477] ERROR in app: Exception on /api/src/subdomain [GET]
Traceback (most recent call last):
  File "/usr/local/bin/python3/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/bin/python3/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/bin/python3/lib/python3.8/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/bin/python3/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/bin/python3/lib/python3.8/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/root/bayonet/web/route/src/api.py", line 271, in get
    data1['loudong_count'] = len(i.src_vulnerabilitie)
AttributeError: 'SrcSubDomain' object has no attribute 'src_vulnerabilitie'
222.209.84.125 - - [25/Mar/2020 14:10:54] "GET /api/src/subdomain?page=1&limit=20&searchParams=%7B%22subdomain%22%3A%22%22%2C%22subdomain_ip%22%3A%22%22%7D HTTP/1.1" 500 -
```

**Comment by handbye** [comment]
数据库中看了下，src_vulnerabilitie 表是空的。

**Comment by CTF-MissFeng** [comment]
> 数据库中看了下，src_vulnerabilitie表是空的。

忘记修改这点了，将这里的改为0，不显示漏洞情况，因为已取消该表的关联。项目代码已更新。感谢反馈。
![image](https://user-images.githubusercontent.com/38177965/77531547-1271fd00-6ece-11ea-8bee-a8eca2847deb.png)

**Comment by handbye** [comment]
此问题已解决，另外是否可以批量添加主域名呢。
