### ISSUE TITLE
数据库连接问题

### ISSUE THREAD

**Issue by cqkenuo** [CTF-MissFeng/bayonet#5]
SQLALCHEMY_DATABASE_URI = 'postgresql://bayonet:aCymcibCp8RN@localhost:5432/bayonet'  
我的数据库配置连接没问题呀！但是就是在插入数据库的时候报错！我数据库版本为11版本

**Comment by CTF-MissFeng** [comment]
> SQLALCHEMY_DATABASE_URI ='postgresql：//刺刀：aCymcibCp8RN @ localhost：5432 / bayonet'
> 我的数据库配置连接没问题呀！但是就是在插入数据库的时候报错！我数据库版本为11版本

请给出插入数据库的错误详情

**Comment by cqkenuo** [comment]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 22, in <module>
    CreateDatabase()  # 创建数据
  File "app.py", line 8, in CreateDatabase
    DB.create_all()
  File "/usr/local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 1033, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/usr/local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 1025, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4316, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2048, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2040, in _optional_conn_ctx_manager
    with self._contextual_connect() as conn:
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2242, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2280, in _wrap_pool_connect
    e, dialect, self
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1547, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 482, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib64/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "bayonet" does not exist

(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by CTF-MissFeng** [comment]
> sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL: database "bayonet" does not exist

最后一行错误提示：sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL: database "bayonet" does not exist，数据库不存在，需要自己创建一个空数据库。

**Comment by cqkenuo** [comment]
我创建了这个数据库的

**Comment by SecReXus** [comment]
我也出现这个问题。我也创建了这个数据库。

**Comment by SecReXus** [comment]
需要去数据库pg_hba.conf配置文件，允许md5登录
![image](https://user-images.githubusercontent.com/19652256/75643833-25046800-5c7b-11ea-8eed-4c852a9c6ca1.png)
详情可以看这个：https://www.cnblogs.com/cyh2009/p/8564406.html
