### ISSUE TITLE
开始进行子域名入库时报错

### ISSUE THREAD

**Issue by linlinzongzongmingjiyuxin** [CTF-MissFeng/bayonet#82]
01:14:05,855 [INFOR] resolve:170 - 完成异步查询子域的A记录
01:14:05,890 [ERROR] database:42 - ('This result object does not return rows. It has been closed automatically.',)
01:14:05,902 [ERROR] database:42 - ('This result object does not return rows. It has been closed automatically.',)
01:14:05,905 [INFOR] dbexport:65 - 开始进行子域名入库
Traceback (most recent call last):
  File "run_subdomain.py", line 4, in <module>
    tools.oneforall.Run.main()
  File "/home/cem/Desktop/src/tools/oneforall/Run.py", line 44, in main
    action(results.domain)
  File "/home/cem/Desktop/src/tools/oneforall/Run.py", line 33, in action
    OneForAll(domain).run()
  File "/home/cem/Desktop/src/tools/oneforall/oneforall.py", line 202, in run
    self.main()
  File "/home/cem/Desktop/src/tools/oneforall/oneforall.py", line 160, in main
    dbexport.Warehouse(resolve_table, self.domain)
  File "/home/cem/Desktop/src/tools/oneforall/dbexport.py", line 69, in Warehouse
    if i.ips:
  File "/usr/local/python3/lib/python3.8/site-packages/records.py", line 65, in __getattr__
    return self[key]
  File "/usr/local/python3/lib/python3.8/site-packages/records.py", line 56, in __getitem__
    i = self.keys().index(key)
AttributeError: 'RMKeyView' object has no attribute 'index'

**Comment by Jamielxl** [comment]
请问有联系方式吗？想请教几个问题
